# PDF Tools

*aka majordome_utilities.pdftools*

```{python}
from majordome_utilities.documents import *
from majordome_utilities.pdftools import *
```

## PdfToTextConverter

Below we illustrate the usage of `PdfToTextConverter`. Please notice that data curation of extracted texts is still required if readability is a requirement. If quality of automated extractions is often poor for a specific language, you might want to search the web how to *train tesseract*, that topic is not covered here.

**Note:** this note assumes [tesseract](https://github.com/tesseract-ocr/tesseract) and [poppler](https://github.com/oschwartz10612/poppler-windows), and [ImageMagick](https://imagemagick.org/) are available in system path. Under Windows you might struggle to get them all working together, please check Majordome's Kompanion for automatic installation.

Install dependencies on Ubuntu 22.04:

```bash
sudo apt install tesseract-ocr imagemagick poppler-utils
```

In case of Rocky Linux 9:

```bash
sudo dnf install tesseract tesseract-langpack-eng ImageMagick poppler-utils
```

Assuming the dependencies are found in the path, it is simply a matter of creating a converter:

```{python}
#| echo: true
converter = PdfToTextConverter()
```

For generated PDF (not scanned documents), it is much faster to avoir using OCR; below we show the metadata from a paper:

```{python}
#| echo: true
data = converter("data/docs/paper.pdf", use_ocr=False)
data.meta
```

For scanned documents, by default if OCR is not enabled it will be used as a fallback method for text extraction:

```{python}
#| echo: true
data = converter("data/docs/scanned.pdf", last_page=1)
data.content[:500]
```
