# Plotting

*aka majordome_utilities.plotting*

```{python}
from majordome_utilities.documents import *
from majordome_utilities.plotting import (
    MajordomePlot,
    PowerFormatter,
    centered_colormap,
)
import numpy as np
import pyvista as pv

pv.set_plot_theme("document")
pv.set_jupyter_backend("static")
```

## MajordomePlot

One might ask why a wrapper around Matplotlib's `Figure` and `Axes` is necessary, and I would strongly agree that it isn't. However, keeping all the plots in a report consistent is a huge effort, and being able to standardize the plots without having to write new themes is a nice feature. That's the main goal of `MajordomePlot`.

```{python}
doc = DocumentedClass(MajordomePlot)
doc.constructor()
```

Let's see how one would expect to use it from the above constructor signature. This is in fact almost the same as calling `plt.subplots()`, and that is what the constructor does under the hood. This is a *negative* example actually, the author has *never* used the constructor directly, but instead uses the `new` classmethod, which is a much more convenient way to create a plot. More on that later.

```{python}
#| echo: true
x = np.linspace(0, 10, 100)
mp = MajordomePlot(shape=(1, 1), size=(5, 4))
mp.axes[0].plot(x, np.sin(x))
mp.axes[0].set_xlabel("x")
mp.axes[0].set_ylabel("sin(x)")
pass
```

The story behind this class dates a few years back, when I was learning about Python decorators. As an exercise, I coded what later became the `new` classmethod, which is a decorator that creates a new `MajordomePlot` and passes it to the decorated function. This is a very convenient way to create plots, as it allows you to focus on the plotting code and not worry about the boilerplate of creating the plot and setting the labels.

```{python}
doc.classmethods()
```

In the following example, we make use of this decorator to parametrize the labels of the plot. Internally, we must expect a *keyword-only* argument `plot`, which is the `MajordomePlot` instance created by the decorator, from which we can access the `Figure` and `Axes` objects as usual. The rest of the code is just standard Matplotlib code, with the exeption that the axes is raveled, so we can access it with `ax[0]` instead of `ax[0, 0]`. Returning `plot` is optional (it is done by the decorator already), but it avoids linting errors if you want to annotate the return type as `MajordomePlot`.

```{python}
#| echo: true
@MajordomePlot.new(size=(5, 4), xlabel="x", ylabel="sin(x)")
def plot_sin(x, *, plot, **kwargs) -> MajordomePlot:
    _, ax = plot.subplots()
    ax[0].plot(x, np.sin(x))
    return plot

plot = plot_sin(np.linspace(0, 10, 100))
```

The following elements document the members and properties of the class.

```{python}
doc.members()
```

```{python}
doc.properties()
```

## PowerFormatter

```{python}
entry = SignatureEntry(PowerFormatter)
entry.documentation()
```

```{python}
def saddle(X, Y):
    return 2 * (X - 5) * (Y - 5)


@MajordomePlot.new(size=(5, 4), xlabel="x", ylabel="exp(x)")
def plot_saddle(x, *, plot, **kwargs) -> MajordomePlot:
    X, Y = np.meshgrid(x, x)
    Z = saddle(X, Y)

    zmin, zmax = Z.min(), Z.max()
    zstep = (zmax - zmin) / 10

    ticks = np.round(np.arange(zmin, zmax + 1, zstep))
    extend = (x.min(), x.max(), x.min(), x.max())

    fig, ax = plot.subplots()
    im = ax[0].imshow(Z, extent=extend, cmap="seismic")

    cbar = fig.colorbar(im, ax=ax[0], shrink=0.95)
    cbar.set_label("Dummy Spectral Density", rotation=270, labelpad=15)
    cbar.set_ticks(ticks)
    cbar.ax.yaxis.set_major_formatter(PowerFormatter())

    return plot

plot = plot_saddle(np.linspace(0, 10, 100))
```

## General utilities

```{python}
entry = SignatureEntry(centered_colormap)
entry.documentation()
```

```{python}
cmap = centered_colormap("seismic", vmin=0, vmax=1, vcenter=0.75)

obj = pv.Sphere(radius=1, center=(0, 0, 0))
x, y, z = obj.points.T

f = 5 * x * y * z
f -= f.min()
f = f / (f.max() - f.min())

p = pv.Plotter()
p.add_mesh(obj, scalars=f, cmap=cmap)
p.show()
```
