#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

rm -rf [0-9]*
rm -rf constant/polyMesh/
rm -rf logging
rm -rf postProcessing
rm -rf processors*
rm -rf VTK

#------------------------------------------------------------------------------
