project:
  type: book

execute:
  cache:   true
  echo:    false
  warning: false

bibliography: _docs/references.bib

book:
  title: "Majordome"
  author: "Walter Dal'Maz Silva"
  date: "today"
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1

  chapters:
    - index.qmd
    - majordome_utilities/documents.qmd
    - majordome_utilities/plotting.qmd
    - _docs/developers.qmd
    - _docs/references.qmd

format:
  html:
    highlight-style: github
    theme:
      - pulse

  pdf:
    highlight-style: github
    documentclass: scrreprt
    papersize: a4
    mainfont: "Latin Modern Sans"
    sansfont: "Latin Modern Sans"
    geometry:
      - margin=25mm
