[package]
name = "majordome"
description = "General utilities for scientific Python and numerical simulation."
repository = "https://github.com/wallytutor/python-majordome.git"
license-file = "LICENSE"
version = "1.5.0"
edition = "2024"
build = "crates/_core/build.rs"

[lib]
name = "_core"
path = "crates/_core/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies.majordome_constants]
path = "crates/majordome-constants"
package = "majordome-constants"

[dependencies.majordome_numerical]
path = "crates/majordome-numerical"
package = "majordome-numerical"

[dependencies.majordome_utilities]
path = "crates/majordome-utilities"
package = "majordome-utilities"

[dependencies.majordome_calphad]
path = "crates/majordome-calphad"
package = "majordome-calphad"

[dependencies.majordome_equations]
path = "crates/majordome-equations"
package = "majordome-equations"

[dependencies.majordome_foam]
path = "crates/majordome-foam"
package = "majordome-foam"

[dependencies.pyo3]
version = "0.28.2"
features = ["extension-module", "abi3-py312", "multiple-pymethods"]

[dependencies.mlua]
version = "0.11"
features = ["lua54", "vendored"]

[dependencies.serde_json]
version = "1"
