[package]
name = "majordome"
description = "General utilities for scientific Python and numerical simulation."
repository = "https://github.com/wallytutor/python-majordome.git"
license-file = "LICENSE"
version = "1.4.0"
edition = "2024"
build = "src/build.rs"

[lib]
name = "_core"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

# For local development (avoid cloning, uncomment the 'path' lines)!
[dependencies.majordome_constants]
# path = "../majordome-constants"
git = "https://github.com/wallytutor/majordome-constants.git"
package = "majordome-constants"

[dependencies.majordome_numerical]
# path = "../majordome-numerical"
git = "https://github.com/wallytutor/majordome-numerical.git"
package = "majordome-numerical"

[dependencies.majordome_utilities]
# path = "../majordome-utilities"
git = "https://github.com/wallytutor/majordome-utilities.git"
package = "majordome-utilities"

[dependencies.majordome_calphad]
# path = "../majordome-calphad"
git = "https://github.com/wallytutor/majordome-calphad.git"
package = "majordome-calphad"

[dependencies.majordome_equations]
# path = "../majordome-equations"
git = "https://github.com/wallytutor/majordome-equations.git"
package = "majordome-equations"

[dependencies.majordome_foam]
# path = "../majordome-foam"
git = "https://github.com/wallytutor/majordome-foam.git"
package = "majordome-foam"

[dependencies.pyo3]
version = "0.28.2"
features = ["extension-module", "abi3-py312", "multiple-pymethods"]

[dependencies.mlua]
version = "0.11"
features = ["lua54", "vendored"]

[dependencies.serde_json]
version = "1"
