# Engineering

*aka majordome.engineering*

```{python}
from majordome.documents import *
from majordome.engineering import *
from majordome.utilities import MajordomePlot, bounds, plot_xy
from casadi import SX, Function, jacobian
from tabulate import tabulate
import cantera as ct
import numpy as np
```

## Reactor models

### Warnings

Module warnings can be controlled throught the following attributes:

```{python}
SignatureEntry(toggle_reactor_warnings).documentation()
```

<!-- This code was deprecated, should I get it back?
They can also be provided to the global `toggle_warnings`, which handles the equivalent function all `majordome` modules. Here we call it with no arguments so all warnings are toggled (and thus this example will be less polluted with warnings intentionaly promoted).
-->

### Utilities

Let's start by creating a standard Cantera solution:

```{python}
#| echo: true
solution = ct.Solution("airish.yaml")
solution.TPY = 273.15, ct.one_atm, "N2: 0.78 O2: 0.21, AR: 0.01"
```

Conversion of composition strings with name filtering is available:

```{python}
SignatureEntry(composition_to_dict).documentation()
```

```{python}
#| echo: true
composition_to_dict("O2: 1, teste: 1", solution.species_names)
```

It is also possible to set unit composition with species names; if you do not provide a validation list, all are are kept:

```{python}
#| echo: true
composition_to_dict("O2, N2, hello")
```

When working with arrays, take care not to end up in the following situation:

```{python}
#| echo: true
composition_to_array(", teste: 1", solution.species_names)
```

There is also a helper for generating inputs for use with `tabulate.tabulate`:

```{python}
SignatureEntry(solution_report).documentation()
```

```{python}
#| echo: true
data = solution_report(solution, specific_props=True,
                       composition_spec="mass", selected_species=[])
print(tabulate(data))
```

Because sometimes Cantera lacks hard-copy utilities for certain classes, we provide simple wrappers that create new instances and set the state to the same of the source object. Nothing checked, nothing tested. A first of this kind is `copy_solution`, illustrated below:

```{python}
SignatureEntry(copy_solution).documentation()
```

```{python}
#| echo: true
newairs = copy_solution(solution)
newairs.TPX = 373.15, None, newairs.X
print(tabulate(solution_report(newairs)))
```

```{python}
#| echo: true
print(tabulate(solution_report(solution)))
```

In addition to this, there is `copy_quantity`, which proves quite useful in establishing an *algebra* of mixtures.

```{python}
SignatureEntry(copy_quantity).documentation()
```

```{python}
#| echo: true
air = copy_solution(solution)

air1 = ct.Quantity(air, mass=1.0)
air1.TPX = 373.15, None, newairs.X

air2 = copy_quantity(air1)
air2.TPX = 273.15, None, air2.X

mixair = air1 + air2
air1.T, air2.T, mixair.T
```

### NormalFlowRate

Common daily work activity for the process engineer is to perform mass balances, but wait, ..., gas flow rates are generally provided under normal conditions, and compositions may vary, so you need to compute normal densities first... whatever. This class provides a calculator wrapping a Cantera solution object so that your life gets easier.

```{python}
SignatureEntry(NormalFlowRate).documentation()
```

Its simples use case is as follows:

```{python}
#| echo: true
nfr = NormalFlowRate("airish.yaml")
print(f"Convert 1000 Nm³/h to {nfr(1000.0):.5f} kg/s")
```

If the database file default composition does not suit you, no problems:

```{python}
#| echo: true
nfr = NormalFlowRate("airish.yaml", X="N2: 1")
print(f"Convert 1000 Nm³/h to {nfr(1000.0):.5f} kg/s")
```

You can also print a nice report to inspect the details of internal state. For more, please check its API documentation.

```{python}
#| echo: true
print(nfr.report())
```

### Plug-flow reactors

### PlugFlowAxialSources

```{python}
SignatureEntry(PlugFlowAxialSources).documentation()
```

#### PlugFlowChainCantera

```{python}
SignatureEntry(PlugFlowChainCantera).documentation()
```

<!-- TODO document methods -->

```{python}
SignatureEntry(get_reactor_data).documentation()
```

## Energy models

This module is concerned with providing classes for computation of energy sources; these are mostly related to estimation of fuel consumption or integration to another simulation modules. Hereafter we illustrate the in cascading complexity the available energy sources. Some of these are simple wrapper around features provided by the combustion utilities.

### CombustionAtmosphereCHON

A common need in industry is to evaluate the real heating value from a gas composition reported by the supplier. This is the main goal of `CombustionAtmosphereCHON`, which has a very simple API provided below:

```{python}
#| echo: true
gas = CombustionAtmosphereCHON("gri30.yaml")
lhv = gas.solution_heating_value("CH4: 1", "O2: 1")
print(f"Solution heating value: {lhv:.2f} MJ/kg")
```

### CombustionPowerSupply

Built upon `CombustionAtmosphereCHON`, `CombustionPowerSupply` performs the basic calculations for retrieving required flow rates from a given power specification; this proves very handy for the CFD engineer.

```{python}
#| echo: true
supply = CombustionPowerSupply(500.0, 1.0, "CH4: 1", "O2: 1", "gri30.yaml")
print(supply.report())
```

<!-- **TODO:** missing a sample with `CombustionAtmosphereMixer`! -->

### Energy sources

#### HeatedGasEnergySource

```{python}
#| echo: true
source = HeatedGasEnergySource("airish.yaml", 500.0, mass_flow_rate=1.0)
print(source.report())
```

```{python}
#| echo: true
source = HeatedGasEnergySource("airish.yaml", 500.0, mass_flow_rate=1.0,
                               cross_area=0.1, Y="N2: 0.79, O2: 0.21")
print(source.report())
```

#### CombustionEnergySource

```{python}
#| echo: true
fuel_state = StateType("CH4: 1",             300, 101325)
oxid_state = StateType("N2: 0.79, O2: 0.21", 300, 101325)
```

```{python}
#| echo: true
ops = CombustionPowerOp(500.0, 1.0, fuel_state, oxid_state)
source = CombustionEnergySource("ch4/bfer.yaml", operation=ops, cross_area=0.1)

# Recover values for other tests that follow
# TODO wrap these in properties for clean API:
mdot_fuel = source._qty_fuel.mass
mdot_oxid = source._qty_oxid.mass

nfr_fuel = NormalFlowRate.new_from_solution(source._qty_fuel)
nfr_oxid = NormalFlowRate.new_from_solution(source._qty_oxid)

qdot_fuel = 3600 * mdot_fuel / nfr_fuel.density
qdot_oxid = 3600 * mdot_oxid / nfr_oxid.density

print(source.report())
```

```{python}
#| echo: true
ops = CombustionFlowOp("mass", mdot_fuel, mdot_oxid, fuel_state, oxid_state)
source = CombustionEnergySource("ch4/bfer.yaml", operation=ops, cross_area=0.1)
print(source.report())
```

```{python}
#| echo: true
ops = CombustionFlowOp("volume", qdot_fuel, qdot_oxid, fuel_state, oxid_state)
source = CombustionEnergySource("ch4/bfer.yaml", operation=ops, cross_area=0.1)
print(source.report())
```

## Numerical utilities

### Relaxation and convergence check utilities

Simplest of relaxation methods; assume you have a new updated solution $A_{new}^{\star}$ for a problem whose past state was $A_{old}$, then the manager will ensure the following relaxation will be applied to compute the next solution state $A_{new}$ to be used in whatever you are computing:

$$
\begin{aligned}
A_{new} &= \alpha{}A_{old} + (1-\alpha)A_{new}^{\star}\\
A_{old} &= A_{new}
\end{aligned}
$$

Notice that in this formulation, $\alpha$ (or `alpha` in the API) represents the fraction of old solution to be used in the *smearing* process. Below we illustrate the effect of a step function $H$ valued at `10` from the begining over consecutive updates (here we do not test for convergence, as that is problem specific and for this simple case the required number of steps could be evaluated by hand, take some time to try!).

```{python}
@MajordomePlot.new(size=(8, 5))
def plot_history(history, *, plot=None):
    """ Plot relaxation history. """
    fig, ax = plot.subplots()

    ax[0].plot(history)
    ax[0].set_title("Verification of relaxation progress")
    ax[0].set_xlabel("Update iteration")
    ax[0].set_ylabel("Updated value")
```

```{python}
#| echo: true
alpha = 0.76
niter = 50

single = np.ones(1)
relaxer = RelaxUpdate(single, alpha)

opts = dict(n_vars=1, max_iter=niter, patience=3, rtol=0.001)
converged = StabilizeNvarsConvergenceCheck(**opts)

history = np.zeros(niter+1)
history[0] = single[0]

H = np.asarray([10])

for n in range(niter):
    single[:] = relaxer(H)
    history[n+1] = single[0]

    if converged(single[0]):
        history = history[:n+2]
        break

_ = plot_history(history)
```

#### RelaxUpdate

```{python}
doc = DocumentedClass(RelaxUpdate)
doc.constructor()
doc.members()
doc.dunders()
```

#### StabilizeNvarsConvergenceCheck

```{python}
doc = DocumentedClass(StabilizeNvarsConvergenceCheck)
doc.constructor()
doc.members()
doc.dunders()
doc.properties()
```


#### ComposedStabilizedConvergence

```{python}
doc = DocumentedClass(ComposedStabilizedConvergence)
doc.constructor()
doc.members()
doc.dunders()
doc.properties()
```

## Symbolic functions

This module contains utilities for working with symbolic functions, especially in the context of engineering problems treated by Majordome models. It is mostly a wrapper around [CasADi](https://web.casadi.org/), organizing symbolic operations and providing additional functionality for function manipulation in a physical context.

### PiecewiseFunction

A major issue when working with symbolic expressions and real-world data is that they do not support flow-control constructs like `if` statements. This is a problem when we want to represent functions that are defined piecewise, especially when algorithmic differentiation is involved.

As an example, take the parameterization of [thermodynamic properties](https://cantera.org/stable/reference/thermo/species-thermo.html) of chemical species. For quantitative purposes, to ensure high accuracy, researchers have found that it is best to use different polynomial fits for different temperature ranges. This means that the thermodynamic properties of a species are defined as piecewise functions of temperature, which is a problem when we want to use them in a symbolic context.

To tackle this issue in *certain* contexts, `PiecewiseSymbolicFunction` provides an interpolation between different ranges of the domain of a function. Internally it makes use of Heaviside functions to ensure that the function is continuous. This is not a perfect solution, as it does not guarantee differentiability at the breakpoints, but it is a good compromise between accuracy and simplicity. It is also worth noting that this class is not meant to be used in a general context, but rather in specific contexts where the function is known to be well-behaved.

```{python}
doc = DocumentedClass(PiecewiseSymbolicFunction)
doc.constructor()
```

Let's illustrate its use with a simple example. We define two functions `f` and `g`, and we want to create a piecewise function that is equal to `f` for `x < 0.5` and equal to `g` for `x >= 0.5`. Functions have being created such that they evaluate to the same value at the breakpoint, as the practical case that led to the class development, *i.e.* NASA-parameterization of thermochemical properties. Below we show how to create the piecewise function, evaluate it numerically and symbolically, and compute its derivative symbolically.

```{python}
#| echo: true
# Define two simple functions:
f = lambda x: x**2
g = lambda x: f(0.5) + (x - 0.5)

# Create the piecewise function:
F = PiecewiseSymbolicFunction([0, 0.5, 1], [f, g])

# Evaluate numerically:
x = np.linspace(-0.2, 1.2, 100)
y = F(x)

# Evaluate symbolically:
T = SX.sym("T")
Y = F(T)

# Create a function for evaluating the derivative:
ydot = Function("fdot", [T], [jacobian(Y, T)])
```

Below we plot the piecewise function and its derivative. The function is continuous, but the derivative is not, as expected, although the transition is handled smoothly by the Heaviside functions. The red dashed line indicates the breakpoint at `x = 0.5`, where the function transitions from `f` to `g`.

```{python}
plot = plot_xy(x, y, label="Piecewise function")
plot.axes[0].plot(x, ydot(x), label="Derivative")
plot.axes[0].axvline(0.5, color="r", linestyle="--")
plot.axes[0].legend(loc=2, fontsize="small")
plot.axes[0].set_ylim(-0.1, 1.1)
pass
```

### Species thermodynamics

```{python}
doc = SignatureEntry(symbolic_thermo_factory)
doc.documentation()
```

Suppose you need to create a symbolic representation of the NASA7 thermodynamic parameterization of molecular nitrogen, species of index 47 in the GRI-Mech 3.0 mechanism shipped with Cantera. Let's start by loading and retrieving the thermodynamic data for this species.

```{python}
#| echo: true
gas = ct.Solution("gri30.yaml")
species = gas.species()[47]
thermo = species.thermo
```

Below we instantiate `SymbolicThermo` with the input data of the species. It is important to emphasize here that when building more complex systems, generally one should share the symbolic variables, *e.g.* temperature, across the different components of the system. For this reason, the constructor of symbolic thermodynamic classes expect the temperature symbol to be provided, instead of trying to create it internally; this is a design choice that will improve code robustness when handling mixtures and avoid many of the pitfalls of symbolic programming.

```{python}
#| echo: true
T = SX.sym("T")
nasa7 = symbolic_thermo_factory(species, T)
```

::: {.callout-note title="Practical usage"}

You could instead directly instantiate `Nasa7Thermo` with the input data,  but using the factory method `SymbolicThermo.from_species` is a better choice, as it will allow you to easily switch to a different thermodynamic model. Furthermore, it is the safe choice for loading entire databases.

```python
nasa7 = Nasa7Thermo(T, species.thermo.input_data)

# This is just syntactic sugar for the above:
nasa7 = Nasa7Thermo.from_species(species, T)
```

:::

Here we illustrate the use of algorithmic differentiation to compute the derivative of the specific enthalpy with respect to temperature.

```{python}
#| echo: true
hdot = Function("hdot", [T], [jacobian(nasa7.h(T), T)])
```

The above derivative is  then confronted to the specific heat below:

```{python}
T_num = np.linspace(500, 2500, 100)

plot = plot_xy(T_num, nasa7.cp(T_num), label="$c_{p}$")
plot.axes[0].plot(T_num[::5], hdot(T_num[::5]), "o", label="$dh/dT$")

for b in nasa7.breakpoints[1:-1]:
    plot.axes[0].axvline(b, color="r", linestyle="--")

plot.axes[0].set_xlabel("Temperature (K)")
plot.axes[0].set_ylabel("Dimensionless specific heat")
plot.axes[0].legend(loc=4)
pass
```

Finally, we compare the deviations between symbolic and numerical (Cantera) evaluation of the thermodynamic functions. This is not for error analysis, but a proof of correctness of the symbolic implementation.

```{python}
#| echo: true
# XXX: Cantera evaluates quantities per kmol! Divide by 1000 to get
# per mol, as the symbolic implementation does.
c_ct = np.array([0.001 * species.thermo.cp(T) for T in T_num])
h_ct = np.array([0.001 * species.thermo.h(T) for T in T_num])
s_ct = np.array([0.001 * species.thermo.s(T) for T in T_num])

error_c = np.mean(np.abs(nasa7._cp(T_num) - c_ct))
error_h = np.mean(np.abs(nasa7._h(T_num) - h_ct))
error_s = np.mean(np.abs(nasa7._s(T_num) - s_ct))

error_c, error_h, error_s
```

#### Nasa7Thermo

```{python}
doc = DocumentedClass(Nasa7Thermo)
doc.constructor()
```

```{python}
doc.staticmethods()
```

```{python}
doc.classmethods()
```

### Species transport

```{python}
doc = SignatureEntry(symbolic_transport_factory)
doc.documentation()
```

### Kinetics parameterization

```{python}
pass
```

### Solution properties

```{python}
pass
```

## Transport properties

### EffectiveThermalConductivity

Class `EffectiveThermalConductivity` implements static methods for the evaluation of properties; its name is quite long, let's start by getting an alias before evaluating the desired models:

```{python}
#| echo: true
etc = EffectiveThermalConductivity()
```

Using [Maxwell](https://en.wikipedia.org/wiki/Effective_medium_approximations) approximation, we could estimate the the effective thermal conductivity of a packed bed of particles in a *matrix* of air; assume particles loosly embeded in air and the following properties; the computed effective thermal conductivity is shown to approach the air limit:

```{python}
#| echo: true
phi = 0.30   # Loosely packed solids [30%v]
k_g = 0.025  # Air thermal conductivity [W/(m.K)]
k_s = 1.000  # Solids thermal conductivity [W/(m.K)]

etc.maxwell_garnett(phi, k_g, k_s)
```

For the limit of high temperatures, it is usually important to account for particle-particle radiation heat transfer; this introduces a $T^3$ dependence on temperature, as one should expect by linearizing Stefan-Boltzmann law.

Please notice that these models compute different things; while Maxwell approximation computes the medium properties (to approximate matrix-inclusion as a single domain), Singh's model accounts only for solids properties. One might wish to combine them (warning: unverified validity!) to evaluate overall medium thermal conductivity. See the references in the class documentation for further discussion, specially the extension proposed by Kiradjiev (2019), which leads to a result similar to the assymptotic behavior displayed below.

```{python}
@MajordomePlot.new(shape=(1, 2))
def plot_etc(data, plot=None):
    fig, ax = plot.subplots()
    T, k_s, k_m =  data

    ax[0].plot(T, k_s)
    ax[1].plot(T, k_m)

    ax[0].set_xlim(bounds(T))
    ax[1].set_xlim(bounds(T))

    ax[0].set_title("Solids property")
    ax[1].set_title("Medium property")
    ax[0].set_xlabel("Temperature [K]")
    ax[1].set_xlabel("Temperature [K]")
    ax[0].set_ylabel("Thermal conductivity [W/(m.K)]")
    ax[1].set_ylabel("Thermal conductivity [W/(m.K)]")
```

```{python}
#| echo: true
d_p = 0.005
eps = 0.9

T = np.linspace(300, 1500, 50)
k_eff_s = etc.singh1994(T, phi, d_p, k_s, eps)
k_eff_m = etc.maxwell_garnett(phi, k_g, k_eff_s)

plot_etc((T, k_eff_s, k_eff_m)).resize(10, 5)
```

Due to kinetic theory implications, gas thermal conductivity tend to have a positive slope in temperature; the following illustrates how this can be accounted for and the roughly linear behaviour introduced when computing medium properties within air.

```{python}
@MajordomePlot.new(shape=(1, 2))
def plot_etc(data, plot=None):
    fig, ax = plot.subplots()
    T, k_g, k_m =  data

    ax[0].plot(T, k_g)
    ax[1].plot(T, k_m)

    ax[0].set_xlim(bounds(T))
    ax[1].set_xlim(bounds(T))

    ax[0].set_title("Fluid property")
    ax[1].set_title("Medium property")
    ax[0].set_xlabel("Temperature [K]")
    ax[1].set_xlabel("Temperature [K]")
    ax[0].set_ylabel("Thermal conductivity [W/(m.K)]")
    ax[1].set_ylabel("Thermal conductivity [W/(m.K)]")
```

```{python}
#| echo: true
gas = ct.Solution("airish.yaml")
sol = ct.SolutionArray(gas, (T.shape[0],))
sol.TP = T, None

k_gas = sol.thermal_conductivity
k_eff_m = etc.maxwell_garnett(phi, k_gas, k_eff_s)

plot_etc((T, k_gas, k_eff_m)).resize(10, 5)
```

### SolutionDimless

A dimensionless numbers calculator is provided for gas flows; it currently has a certain number of groups which are all evaluated by definition (which might change according to your field, please check the docs). The mechanics of using the class can be resumed to:

1. loading a mechanism file (Cantera YAML)
2. setting the state of the solution
3. evaluating the required properties
4. (optional) displaying a report

The meaning of the tuple of arguments provided to `set_state` is specified by `tuple_name="TPX"`, which defaults to temperature, pressure, and molar proportions. Any triplet allowed by [Cantera](https://cantera.org/stable/python/thermo.html#id3) can be specified here.

```{python}
#| echo: true
Tw = 1000.0  # Wall temperature [K]
U = 10.0     # Characteristic velocity [m/s]
D = 0.05     # Pipe diameter [m]
L = 1.0      # Pipe length [m]

calculator = SolutionDimless("airish.yaml")
calculator.set_state(300.0, 101325.0, "N2: 1", tuple_name="TPX")

Re   = calculator.reynolds(U, D)
Pr   = calculator.prandtl()
Sc   = calculator.schmidt()
print(calculator.report())
```

If you prefer to have direct access to the internal solution, you can set properties as usual in Cantera, but you need to keep in mind to call `update()` to refresh the internal state of the calculator. Every time the properties are updated, the internal buffer of computed dimensionless numbers is refreshed, as you migth notice in the following table.

```{python}
#| echo: true
calculator.solution.TPX = 300.0, 101325.0, "N2: 1"
calculator.update()

Pe_m = calculator.peclet_mass(U, L)
Pe_h = calculator.peclet_heat(U, L)
Gr   = calculator.grashof(Tw, D)
Ra   = calculator.rayleigh(Tw, D)
print(calculator.report())
```

### SutherlandFitting

To the author's knowledge, there is no standard tool to convert Cantera transport data to Sutherland parameters for use with OpenFOAM, what led to the motivation to develop `SutherlandFitting`. This simple class wraps a Cantera solution object, which it makes use for fitting Sutherland parameters to export as a table (to be used elswhere), and also allows for retrieving a converted database in OpenFOAM compatible format. The following example should be self-explanatory:

```{python}
#| echo: true
T = np.linspace(500, 2500, 100)

sutherland = SutherlandFitting("airish.yaml")
sutherland.fit(T, species_names=["O2", "N2"])

coef = sutherland.coefs_table
coef
```

If needed, it is also possible to have direct access to the viscosity data used in parameter fitting:

```{python}
#| echo: true
sutherland.viscosity.head()
```

Because RMSE compresses all the error in a single value, you can check graphically where the deviations happen in the interval:

```{python}
#| echo: true
plot = sutherland.plot_species("N2")
```

Finally, it *also* responds to its initial goal of exporting values in OpenFOAM format:

```{python}
#| echo: true
print(sutherland.to_openfoam())
```

### WSGGRadlibBordbar2020

Radiative properties of gases are often required when participating media characteristics imply so. Here we implement the WSGG model of @Sadeghi2021 in class `WSGGRadlibBordbar2020`. The basic usage of the model to estimate total emissivity is done as follows:

```{python}
#| echo: true
model = WSGGRadlibBordbar2020()
model(L=1, T=1000, P=101325, x_h2o=0.18, x_co2=0.08, fvsoot=0.0)
```

#### Validation of Bordbar WSGG implementation

Evaluation of the model against original source of Bordbar (2014) is satisfactory, as follows:

```{python}
@MajordomePlot.new(shape=(1, 2))
def plot_bordbar2014(_obj, plot=None):
    """ Reproduce plots of Bordbar (2014), Fig. 2. """
    fig, ax = plot.subplots()

    def scan_flue(T, L, *, M):
        x_co2 = 1 / (1 + M)
        return model(L, T, 101325, M*x_co2, x_co2)

    dry_flue = np.vectorize(lambda T, L: scan_flue(T, L, M=1/8))
    wet_flue = np.vectorize(lambda T, L: scan_flue(T, L, M=1/1))

    L = np.asarray([0.01, 0.1, 0.5, 1.0, 3.0, 5.0, 10.0, 20.0, 60.0])
    T = np.arange(400, 2401, 100)
    sample = np.meshgrid(T, L)

    for n, eps in enumerate(dry_flue(*sample)):
        ax[0].plot(T, eps, label=f"{L[n]} atm.m")

    for n, eps in enumerate(wet_flue(*sample)):
        ax[1].plot(T, eps, label=f"{L[n]} atm.m")

    ax[0].set_title("Dry flue M=1/8")
    ax[1].set_title("Wet flue M=1")

    ax[0].set_xlabel("Temperature [K]")
    ax[1].set_xlabel("Temperature [K]")

    ax[0].set_ylabel("Total emissivity")
    ax[1].set_ylabel("Total emissivity")

    ax[0].set_xlim(400, 2400)
    ax[1].set_xlim(400, 2400)
    ax[0].set_ylim(0, 1)
    ax[1].set_ylim(0, 1)

    ax[0].set_xticks(np.arange(400, 2401, 400))
    ax[1].set_xticks(np.arange(400, 2401, 400))

    ax[0].set_yticks(np.arange(0, 1.01, 0.1))
    ax[1].set_yticks(np.arange(0, 1.01, 0.1))

    ax[0].legend(loc=1, fontsize=9)
    ax[1].legend(loc=1, fontsize=9)
```

```{python}
plot_bordbar2014(None).resize(10, 5)
```

Absorption coefficients for pure substances only reproduce approximately values reported by Bordbar (2020).

```{python}
#| echo: true
model(L=1, T=300, P=101325, x_h2o=0, x_co2=1)
model.absorption_coefs[1:]
```

```{python}
#| echo: true
model(L=1, T=300, P=101325, x_h2o=1, x_co2=0)
model.absorption_coefs[1:]
```

#### Application to radiative combustion

Below we illustrate the application of `WSGGRadlibBordbar2020` to predict the emissivity of  $x\mathrm{H_2O}-(1-x)\mathrm{CO_2}$ mixtures over a broad temperature range applicable to the analysis of combustion processes. One observes an important participation of flue gases, especially at lower temperatures.

```{python}
@MajordomePlot.new(size=(6, 5),
                   xlabel="Temperature [K]",
                   ylabel="Water content [-]")
def plot_emissivity(T, X, eps, *, plot=None):
    comp = r"$x\mathrm{H_2O}-(1-x)\mathrm{CO_2}$"
    fig, ax = plot.subplots()
    cf = ax[0].contourf(T, X, eps, cmap="inferno")
    cbar = ax[0].figure.colorbar(cf, ax=ax[0], shrink=0.9)
    ax[0].grid(color="white", alpha=0.5)
    ax[0].set_title(f"Emissivity of {comp}")
```

```{python}
#| echo: true
wsgg = WSGGRadlibBordbar2020()

@np.vectorize
def emissivity(T, X, L=1, P=101325):
    return wsgg(L=L, T=T, P=P, x_h2o=X, x_co2=1-X, fvsoot=0.0)

T = np.linspace(800, 2400, 100)
X = np.linspace(0, 0.7, 100)

T, X = np.meshgrid(T, X)
eps = emissivity(T, X)
plot_emissivity(T, X, eps)
```

## Computer vision

*Upcoming...*
