# Majordome extensions

*aka majordome.magic*

```{python}
from majordome_utilities.documents import *
from majordome.magic import *
```

On top of your notebook, simply load the extension:

```{python}
#| echo: true
# XXX: the following was replaced by `majordome.magic`.
# %load_ext majordome_utilities.skipper

%load_ext majordome.magic
```

## Skipping execution

```{python}
doc = DocumentedClass(SkipperMagic)
doc.constructor()
```

The module provides a simple extension for skipping the execution of code cells in a notebook. It does that and only that. The goal is to control notebook execution from the environment, which is useful when running notebooks with long-running cells, as numerical simulations.

```{python}
#| echo: true
%skipper_verbosity 1
```

Here we will use `sleep` to emulate a long-running cell, and we will control its execution with an environment variable. Generally speaking, the goal is to export environment variables in the terminal before running the notebook, but for demonstration purposes, we will set it in the notebook itself.

```{python}
#| echo: true
from time import sleep
import os
```

The following (case insensitive) options are accepted by the `%%skipper` magic command. Please, notice that the *truthy* values mean *skip this cell* (as the extension name implies, but even myself can be confused by the double negative here).

```{python}
print(SkipperMagic.LOOKUP_STR2BOOL)
```

Below we set the environment variable `SOLVE_LONNNNG` to `true`, which means that the cell will be skipped. You can change it to `false` to execute the cell, or even set it to any other value, as long as it is in the lookup table.

```{python}
#| echo: true
os.environ["SOLVE_LONNNNG"] = "true"

did_you_skip_it = True
```

If everything is file, the following cell will be skipped:

```{python}
#| echo: true
%%skipper SOLVE_LONNNNG
sleep(100)
did_you_skip_it = False
```

And here we check if it was actually skipped:

```{python}
#| echo: true
print("Did you skip it?", did_you_skip_it)
```

You can also avoid the *Skipping cell* message by setting the verbosity to `0`:

```{python}
#| echo: true
%skipper_verbosity 0
```

```{python}
#| echo: true
%%skipper SOLVE_LONNNNG
sleep(100)
did_you_skip_it = False
```

## Markdown and LaTeX interpolation

```{python}
doc = DocumentedClass(MdMagic)
doc.constructor()
```

Declare some values in the user namespace:

```{python}
#| echo: true
variable = "hello"
some_value = 12.2
```

Below we have a Markdown cell with some variables and LaTeX expressions. The variables will be replaced by their values, and the LaTeX will be rendered correctly.

```{python}
#| echo: true
%%md
I have this string with a variable: {variable}.

There is also some latex: $\int_a^b f(x) \; dx$.

- Some formatter value {some_value:.2f}

- Some block math:

$$
\int_0^\infty e^{-x^2} dx = \frac{\sqrt{\pi}}{2}
$$
```

The following is also possible in math blocks:

```{python}
#| echo: true
%%md

$$
F(x) = {some_value:.2f} \cdot x^2
$$

But there is not way to use the plain `some_value` without a format specifier, as it would be indistinguishable from a regular LaTeX expression.

$$
F(x) = {some_value} \cdot x^2
$$
```
