project:
  type: book

jupyter: python3

execute:
  cache:   true
  echo:    false
  warning: false

book:
  title: Majordome Calphad
  author: Walter Dal'Maz Silva
  date: today
  sidebar:
    style: docked
    search: true
    collapse-level: 2

  chapters:
    - index.qmd
    - parameterizations.qmd

format:
  html:
    reference-location: document
    highlight-style: github
    theme:
      - pulse

  typst: default
