[project]
name = "majordome-foam"
version = "0.1.0"
description = "OpenFOAM dictionary parser and manipulator for Majordome."
readme = "README.md"
authors = [
    { name = "Walter Dal'Maz Silva", email = "walter.dalmazsilva@gmail.com" },
]
requires-python = ">=3.12"
dependencies = ["majordome-build"]

[project.optional-dependencies]
devel = [
    "ipykernel>=7.3.0",
    "pytest>=9.1.1",
]

[tool.maturin]
module-name = "majordome_foam.foam"
python-packages = ["majordome_foam"]
python-source = "src"

[tool.uv]
cache-keys = [
    { file = "pyproject.toml" },
    { file = "src/**/*.rs" },
    { file = "Cargo.toml" },
    { file = "Cargo.lock" },
]

[tool.uv.sources]
majordome-build = { git = "https://github.com/wallytutor/majordome-build.git" }

[tool.pytest.ini_options]
python_files = ["test.py"]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
