# ############################################################################
#  Containerfile.general
# ############################################################################

FROM ubuntu:24.04

# ----------------------------------------------------------------------------
# Basics and avoid locale issues
# ----------------------------------------------------------------------------

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y locales && locale-gen en_US.UTF-8

ENV LANG=en_US.UTF-8     \
    LANGUAGE=en_US:en    \
    LC_CTYPE=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8

RUN update-locale LANG=en_US.UTF-8

# ----------------------------------------------------------------------------
# APT installed tools
# ----------------------------------------------------------------------------

# If the image build breaks (stops installing some of the packages), then it
# may be that the database needs to be updated first; place the failing command
# just after a(nother) copy of the following line:
RUN apt-get update

# Base development toolkit:
RUN apt-get install -y build-essential git gcc g++ gfortran make cmake

# Install curl/wget and software-properties-common for adding repositories:
RUN apt-get install -y curl wget software-properties-common

# Install Python and venv tools:
RUN apt-get install -y python3 python3-venv python3-pip python3-dev

# Other required software:
RUN apt-get install -y pandoc inkscape poppler-utils tesseract-ocr imagemagick

# Linux libraries needed for PyVista/VTK:
RUN apt-get install -y \
    libxrender1 \
    libvtk9-dev \
    libosmesa6 \
    libgl1 \
    libegl1 \
    libgomp1 \
    libtbb12

# ----------------------------------------------------------------------------
# Python environment setup
# ----------------------------------------------------------------------------

RUN add-apt-repository ppa:deadsnakes/ppa -y && \
    apt-get update && \
    apt-get install -y python3.12 python3.12-venv python3.12-dev && \
    apt-get install -y python3.13 python3.13-venv python3.13-dev && \
    apt-get install -y python3.14 python3.14-venv python3.14-dev

# Create a virtual environments:
RUN python3.12 -m venv /opt/python3.12/
RUN python3.13 -m venv /opt/python3.13/
RUN python3.14 -m venv /opt/python3.14/

# Activate venv by using its binaries directly:
ENV PATH="/opt/python3.12/bin:$PATH"
ENV PATH="/opt/python3.13/bin:$PATH"
ENV PATH="/opt/python3.14/bin:$PATH"

# Ensure pip is up to date:
RUN python3.12 -m pip install --upgrade pip build
RUN python3.13 -m pip install --upgrade pip build
RUN python3.14 -m pip install --upgrade pip build

# ----------------------------------------------------------------------------
# RUST
# ----------------------------------------------------------------------------

ENV CARGO_HOME=/opt/cargo
ENV RUSTUP_HOME=/opt/rustup

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path \
    --default-toolchain stable \
    --profile minimal \
    --default-host x86_64-unknown-linux-gnu

# XXX: DO I NEED THIS??
# RUN . "/opt/cargo/env

# Add Rust (Cargo actually) to PATH for all container sessions:
ENV PATH="/opt/cargo/bin:$PATH"

# ----------------------------------------------------------------------------
# HOME
# ----------------------------------------------------------------------------

# Set working directory:
ENV APPHOME=/opt/app
RUN mkdir -p $APPHOME
WORKDIR $APPHOME

# ----------------------------------------------------------------------------
# PRE-INSTALL
# ----------------------------------------------------------------------------

# Pre-install Python dependencies:
# XXX: Python3.14 still needs dependencies to be fixed.
COPY containerfile.txt /opt/app/containerfile.txt
RUN python3.12 -m pip install -r /opt/app/containerfile.txt
RUN python3.13 -m pip install -r /opt/app/containerfile.txt
# RUN python3.14 -m pip install -r /opt/app/containerfile.txt

# Pre-install build tools:
RUN python3.12 -m pip install 'wheel==0.45.1' 'setuptools_rust==1.12.0'
RUN python3.13 -m pip install 'wheel==0.45.1' 'setuptools_rust==1.12.0'
# RUN python3.14 -m pip install 'wheel==0.45.1' 'setuptools_rust==1.12.0'

# ----------------------------------------------------------------------------
# CLEAN UP
# ----------------------------------------------------------------------------

# Clean up and make image smaller:
RUN apt-get clean && rm -rf /var/lib/apt/lists/* && rm -rf /var/tmp/build*

# ############################################################################
# EOF
# ############################################################################