# Fluent files

*aka majordome_simulation.fluent*

```{python}
from majordome_utilities.documents import *
from majordome_simulation.fluent import *
```

## FluentFvParticlesParser

This class provides functionality for parsing particle track files. Fluent export DPM results in several formats; `majordome` supports *fieldview* particle tracks through `FluentFvParticlesParser`. Loading a file is as simple as:

```{python}
dpm = FluentFvParticlesParser("data/docs/sample.fvp")
```

You can retrieve the names of columns and number of individual tracks with the following properties:

```{python}
dpm.variable_names, dpm.n_tracks
```

For convenience, tracks can be recovered as data frames through object indexing:

```{python}
dpm[0]
```

## FluentInterpolationParser

Sometimes is is also useful to parse interpolation files. It enables one to compute new quantites for an interpolation files may be useful, especially in reasearch settings. Class `FluentInterpolationParser` is able to read the contents of an interpolation file exported in plain text format. Below you find an example of parsing.

```{python}
ip = FluentInterpolationParser("data/docs/sample.ip")
```

Names of variables are provided by property `variable_names`:

```{python}
ip.variable_names
```

Valid names can be used to retrieve data for a given variable:

```{python}
ip.get_data("x0")
```

The whole data table can be retreived with `data` property, where each variable correspond to a column:

```{python}
ip.data
```
