# Finite Volume Method

In this course we provide a Finite Volume Method relecture to the famous [The 12 steps to Navier-Stokes equations](https://jose.theoj.org/papers/10.21105/jose.00021), by Lorena A. Barba and Gilbert F. Forsyth. It is not a bare translation, but a different approach to the problems with the addition of new elements, some sort of _Twelve-steps to Navier Stokes rewind_.

Also the final goal has been changed and now it is not only as reaching the implementation of Navier-Stokes equations, but learning the key ideas of finite volumes applied to other fields of interest in Materials Science. Students who are undergoing Calculus training should already meet the minimum requirements to follow this course.

Focus will be given not only on the numerical methods, but also how a computer implementation should look like. This last point is the most distinctive point from the work upon which it is based. A vast amount of learning resources is available for scientific computing, but rare sources really provide guidance for conceiving quality and maintainable code. Here we try to contribute for better coding practices through a *think-before-coding* approach.

<!-- Old FD index for guidance:
1. Introduction to Advection in 1-D
1. Courant-Friedrichs-Lewy Criterium
1. Stability Analysis of Advection Equation
1. Introduction to Diffusion in 1-D
1. Diffusion-Reaction Equation in 1-D
1. Burguers Equation in 1-D
1. Laplace and Poisson equations
1. Navier-Stokes Equation
1. Introduction to Finite Volume Method
1. Fundamentals of Parallel Computing
-->

## Diffusion equation

This part describes the implementation of diffusion using finite volume method. It is intended mainly to treat topics of interest in Materials Science, thus composition and spatial dependencies of diffusivity are a pre-requisite for any practical use case. A progressive level of complexity in the described physics will be considered. It assumes the reader is already familiar with basic concepts of diffusion in solids, much of which will be exposed in the text without further explanations.

The following lists the goals and status of current text:

- [x] Simple Fick's Law with possible nonlinear behavior in one-dimension on [chapter @sec-diffusion-1d].
- [ ] Modification of one-dimensional implementation for non-homogeneous grids.
- [ ] Generalization of Fickean diffusion to higher dimensions and other coordinate systems.
- [ ] Irreversible Thermodynamics approach for chemical potentials.
- [ ] Anisotropy of diffusivities in three-dimensional space.

The interested reader may wish to consult the work by @Mehrer2007 for more details; any Materials Scientist is also recommended at some point to check the classic works of [@Onsager1931;@Onsager1931a].

## Convection equation

_Upcoming_ [here @sec-convection-1d]!
