# Developers

The environment for developing Majordome requires at least a reasonably mondern version of Python and Rust; documentation depends on Quarto and `uv` is preferred over `pip` for managing the environment. The exact versions may change over time, but as of the last update, the following (minimum) versions are recommended:

- [Python 3.12](https://python.org/downloads/)
- [Rust 1.90](https://rust-lang.org/tools/install/)
- [Quarto 1.8](https://quarto.org/docs/get-started/)
- [uv](https://docs.astral.sh/uv/)

The development focuses on portability and ease of setup, so by default any dependency relying on a C/C++ compiler is forbidden. This means that the development environment can be set up on any platform without needing to install additional compilers or tools.

Majordome code is documented using Numpydoc style docstrings, and the documentation is generated by module `majordome.documents` using Quarto markdown. This design choice reflects the academic aim of the package, with reporting and notebook support as first-class citizens. Differently from usual packages, the `.qmd` files live along the modules they document, except for the main documentation file `developers.qmd`, which is located in the `_docs` folder. This allows to keep the documentation close to the code, and to easily update it when the code changes.

To standardize packaging and distribution, build scripts are provided for both Windows PowerShell (`build.ps1`) and Unix-like shells (`build.sh`). These scripts handle the installation of dependencies, building the package, running tests, and generating documentation. The scripts are designed to be user-friendly and to provide clear feedback on the actions being performed. Both share the same command line arguments, which are illustrated below (using `build.ps1` as an example).

- Building the package:

``` bash
# Install the Python package in development mode:
./build.ps1 -PythonEnv py312 -FromPip

# Install the Python package with release optimizations and create wheel:
./build.ps1 -PythonEnv py312 -FromPip -PackageDist -FlagRelease
```

- Documentation builds:

``` bash
# Only HTML documentation:
./build.ps1 -PythonEnv py312 -PackageDocs

# Also generate PDF documentation:
./build.ps1 -PythonEnv py312 -PackageDocs -DocsPdf

# Erase everything and do not use any cached files:
./build.ps1 -PythonEnv py312 -PackageDocs -FreshDocs

# Publish the documentation to GitHub Pages:
./build.ps1 -PythonEnv py312 -PublishDocs
```

- Testing the package:

```bash
# Check Rust code with backtraces enabled.
./build.ps1 -RustCheck -FlagBacktrace

# Run Python tests.
./build.ps1 -TestRust

# Run Python tests.
./build.ps1 -TestPython
```

- For distribution, maintainers can proceed as

```bash
uv pip install --upgrade twine
twine upload --repository majordome dist/*
```

## Manual setup

For developing the package, consider doing so from within a virtual environment; that will makes things easier to check versions and pin them properly in package dependencies, as needed. Following the next snippet, install, activate, upgrade pip, install build tools, and install the package in editable mode with all optional dependencies:

```bash
# Create a virtual environment
python -m venv venv

# Activate the virtual environment (Windows PowerShell)
. venv/Scripts/Activate.ps1

# Activate the virtual environment (Unix-like)
. venv/bin/activate

# Upgrade pip
python -m pip install --upgrade pip

# Install build tools
python -m pip install --upgrade --force-reinstall build wheel
python -m pip install --upgrade --force-reinstall setuptools
python -m pip install --upgrade --force-reinstall setuptools_rust

# Install the package in editable mode with all optional dependencies
pip install -e .[full]
```

Ubuntu users can bootstrap the environment with the following commands; make sure to check the latest versions of the tools and update the commands accordingly.

```bash
sudo apt-get install -y python3-dev

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
source "$HOME/.cargo/env"

curl -LsSf https://astral.sh/uv/install.sh | sh
source "$HOME/.local/bin/env"

quarto_repo="https://github.com/quarto-dev/quarto-cli"
wget $quarto_repo/releases/download/v1.9.37/quarto-1.9.37-linux-amd64.deb
sudo apt-get install -y ./quarto-1.9.37-linux-amd64.deb
```

## Todo lists

- Implement diffusional Grashof number in `majordome_engineering.transport.SutherlandFitting`, which is related to mass transfer arising because of the buoyant force caused by the concentration inhomogeneities.

- Create a data converter to create Ansys Fluent SCM files directly from Cantera YAML (species data and reactions).

- Add generation of TUI commands for Fluent expression generator (and further expand to general Fluent setup).

- Migrate `gpxpy` usage to plain XML for better maintainability.
