# Liens utiles

*This page is intentionally written in French.*


## Géneral


- [Sports de Nature](https://www.sportsdenature.gouv.fr/)



## Cartographie


OpenStreetMap:

- [OpenStreetMap Wiki](https://wiki.openstreetmap.org/)
- [OpenStreetMap Wiki - FR:Projet Plein Air](https://wiki.openstreetmap.org/wiki/FR:Projet_Plein_Air)
- [OpenStreetMap live edits](https://live.openstreetmap.fr/)
- [Forum OSM France](https://forum.openstreetmap.fr/)
- [A summary of things happening in the OpenStreetMap world](https://weeklyosm.eu/)


Cartes pour Garmin:

- [OpenTopopMap](https://garmin.opentopomap.org/#france)
- [numeriquement](https://numeriquement.fr/randonnee/generation_fichier_openstreetmap.php)
- [mkgmap](https://www.mkgmap.org.uk/download/mkgmap.html)


Other sites:

- [Freizeitkarte](https://www.freizeitkarte-osm.de/garmin/en/index.html)
- [OpenTopoMap](https://opentopomap.org/#map=5/49.000/10.000)
- [UtagawaVTT](https://www.utagawavtt.com/)
- [CyclOSM](https://www.cyclosm.org/#map=12/52.3728/4.8936/cyclosm)
- [OpenWhateverMap](https://openwhatevermap.xyz/#3/28.00/18.00)
- [Waymarked Trails](https://waymarkedtrails.org/)
- [Jeux de données - data.gouv.fr](https://www.data.gouv.fr/fr/datasets/?tag=openstreetmap)
- [MyOSMatic](https://print.get-map.org/)
- [MapRoulette](https://maproulette.org/)


## Mobilité douce


- [Partir Ici](https://partir-ici.fr/envies/sport-nature/)
- [SNCF Rhône Alpes - Réservation vélo](https://www.ter.sncf.com/auvergne-rhone-alpes/services-contacts/voyager-avec-velo/embarquement-velo)



## Cyclisme


Vélo de montagne:

- [Sites FFC](https://sitesvtt.ffc.fr/sites/)
- [Cotations de difficulté](https://alpinemag.fr/vtt-cotations-difficulte/)
- [Autour du Pilat](https://www.parc-naturel-pilat.fr/des-decouvertes/randonnee/pilat-a-velo/)
- [Gravel Passion](https://www.gravelpassion.fr/)


Vélo de route:

- [Cols-Cyclisme](https://www.cols-cyclisme.com/)
- [Inforoutes FR](https://www.inforoutefrance.fr/)
- [Inforoutes 04](https://www.inforoute04.fr/)
- [Inforoutes 06](https://www.inforoutes06.fr/)



## Trail running


- [Finishers](https://www.finishers.com/courses)
- [Premier Marathon](https://premier-marathon.com/)



## Neige et glace


- [Data Avalanche](https://www.data-avalanche.org/)
- [CRISTAL](https://www.cristal-avalanche.org/)
- [Ice Climbing Cogne](https://www.iceclimbingcogne.com/)
- [ANENA](https://anena.org/)
- [Skitourenguru](https://www.skitourenguru.ch/)


## Autour de Chamonix


- [Mont-Blanc Natural Resort](https://www.montblancnaturalresort.com/fr/)
