project:
  type: book

jupyter: python3

execute:
  cache:   true
  echo:    false
  warning: false

book:
  title: "Majordome"
  author: "Walter Dal'Maz Silva"
  date: "today"
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2

  chapters:
    - index.qmd

    - part: "Majordome API"
      chapters:
      - _engineering/_index.qmd
      - _simulation/_index.qmd
      - _utilities/_index.qmd
      - magic.qmd

    - part: "Reactor Engineering"
      chapters:
        - reactors/acetylene-pyrolysis-reactor.qmd
        - reactors/counter-current-pfr.qmd
        - reactors/converting-nasa-poly.qmd

    - references.qmd

bibliography: https://raw.githubusercontent.com/wallytutor/wallytutor.github.io/refs/heads/main/shorts/_assets/references.bib

format:
  html:
    reference-location: document
    highlight-style: github
    theme:
      - pulse

  # WIP not yet compiling
  # typst: default
  # typst:
  #   papersize: a4
  #   fontsize: 11pt

  #   margin:
  #     left: 25mm
  #     right: 25mm
  #     top: 25mm
  #     bottom: 25mm

  #   syntax-highlighting: github
  #   include-before-body: assets/custom.typ

  # pdf:
  #   reference-location: document
  #   highlight-style: github
  #   documentclass: scrreprt
  #   papersize: a4
  #   mainfont: "Latin Modern Sans"
  #   sansfont: "Latin Modern Sans"
  #   geometry:
  #     - margin=25mm
