project:
  type: book

execute:
  cache:   true
  echo:    false
  warning: false

book:
  title: "Majordome"
  author: "Walter Dal'Maz Silva"
  date: "today"
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2

  chapters:
    - index.qmd

    - part: "Majordome API"
      chapters:
      - magic.qmd
      - engineering.qmd
      - simulation.qmd
      - utilities.qmd
      - documents.qmd

    - part: "Reactor Engineering"
      chapters:
        - reactors/acetylene-pyrolysis-reactor.qmd
        - reactors/counter-current-pfr.qmd
        - reactors/converting-nasa-poly.qmd

    - references.qmd

bibliography: https://raw.githubusercontent.com/wallytutor/kompanion/refs/heads/main/notes/references.bib

format:
  html:
    reference-location: document
    highlight-style: github
    theme:
      - pulse

  pdf:
    reference-location: document
    highlight-style: github
    documentclass: scrreprt
    papersize: a4
    mainfont: "Latin Modern Sans"
    sansfont: "Latin Modern Sans"
    geometry:
      - margin=25mm
