#!/bin/sh
cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

touch case.foam

cp -avr zero/* .
cp ../components/decomposeParDict system/
cp ../components/blockMeshDict system/
cp ../components/fv* system/
cp ../components/Allclean .

runApplication blockMesh
runApplication potentialFoam
rm -rf 0/phi
runApplication decomposePar
runApplication mpirun -np 32 foamRun -parallel
reconstructPar -latestTime
rm -rf processor*/

cp "postProcessing/residuals(p,U,k,epsilon,h,C7H16)/0/residuals.dat" residuals.ref
tail -52 log.mpirun >> residuals.ref

#------------------------------------------------------------------------------
