# -*- coding: utf-8 -*-
import sys
import os

# Add current directory to path so we can import _calphad
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import _calphad


def main():
    print("========================================")
    # 1. Initialize the DatabaseLoader with standard data
    db_path = "data/data.lua"
    print(f"Loading Calphad database from: {db_path}")
    loader = _calphad.DatabaseLoader(db_path)
    print(f"Database path stored internally: {loader.path}")

    # 2. Retrieve substances as a dictionary
    data = loader.get_data()
    print(f"Database phases: {loader.phases}")
    print(f"Successfully loaded {len(data)} compounds: {list(data.keys())}")
    print("----------------------------------------")

    # 3. Print thermodynamic report of Calcite generated by Rust
    calcite = data["Calcite"]
    print(calcite.report(300.0))
    print("----------------------------------------")

    # 4. Test filtering via constructor
    print("Loading filtered database with only ['Calcite', 'CO2']:")
    loader_filtered = _calphad.DatabaseLoader(db_path, ["Calcite", "CO2"])
    print(f"  Selected phases list: {loader_filtered.phases}")
    filtered_data = loader_filtered.get_data()
    print(f"  Loaded phases in dict: {list(filtered_data.keys())}")

    # 5. Test load_compound retrieving new data
    print("Retrieving 'Lime' compound on-demand using load_compound:")
    lime = loader_filtered.load_compound("Lime")
    print(f"  Successfully loaded: {lime.name}")
    print(f"  Lime Cp at 300K:     {lime.cp(300.0):.4f} J/(mol*K)")
    print(f"  Formation dHf298:    {lime.formation_enthalpy:.4f} J/mol")
    print("========================================")


if __name__ == "__main__":
    main()
