#!/bin/sh

# Run from this directory.
cd ${0%/*} || exit 1

# Source tutorial run functions.
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Prepare and launch case.
restore0Dir
runApplication blockMesh
runApplication decomposePar
runParallel $(getApplication)
runApplication reconstructPar

# Header.
echo "#Time    Nusselt" > Nusselt.dat

# Print results.
grep -e '^Time =' -e '^Space-averaged Nusselt lambda =' log.$(getApplication) | awk -F'=' '/Time =/ {t=$NF} /Space-averaged Nusselt lambda*/ {print t"	"$NF}' >> Nusselt.dat

#------------------------------------------------------------------------------
