# Reactor models

*aka majordome_engineering.reactor*

```{python}
from majordome_utilities.documents import *
from majordome_engineering.reactor import *
from tabulate import tabulate
import cantera as ct
```

## Warnings

Module warnings can be controlled throught the following attributes:

```{python}
SignatureEntry(toggle_reactor_warnings).documentation()
```

<!-- This code was deprecated, should I get it back?
They can also be provided to the global `toggle_warnings`, which handles the equivalent function all `majordome` modules. Here we call it with no arguments so all warnings are toggled (and thus this example will be less polluted with warnings intentionaly promoted).
-->

## Utilities

Let's start by creating a standard Cantera solution:

```{python}
#| echo: true
solution = ct.Solution("airish.yaml")
solution.TPY = 273.15, ct.one_atm, "N2: 0.78 O2: 0.21, AR: 0.01"
```

Conversion of composition strings with name filtering is available:

```{python}
SignatureEntry(composition_to_dict).documentation()
```

```{python}
#| echo: true
composition_to_dict("O2: 1, teste: 1", solution.species_names)
```

It is also possible to set unit composition with species names; if you do not provide a validation list, all are are kept:

```{python}
#| echo: true
composition_to_dict("O2, N2, hello")
```

When working with arrays, take care not to end up in the following situation:

```{python}
#| echo: true
composition_to_array(", teste: 1", solution.species_names)
```

There is also a helper for generating inputs for use with `tabulate.tabulate`:

```{python}
SignatureEntry(solution_report).documentation()
```

```{python}
#| echo: true
data = solution_report(solution, specific_props=True,
                       composition_spec="mass", selected_species=[])
print(tabulate(data))
```

Because sometimes Cantera lacks hard-copy utilities for certain classes, we provide simple wrappers that create new instances and set the state to the same of the source object. Nothing checked, nothing tested. A first of this kind is `copy_solution`, illustrated below:

```{python}
SignatureEntry(copy_solution).documentation()
```

```{python}
#| echo: true
newairs = copy_solution(solution)
newairs.TPX = 373.15, None, newairs.X
print(tabulate(solution_report(newairs)))
```

```{python}
#| echo: true
print(tabulate(solution_report(solution)))
```

In addition to this, there is `copy_quantity`, which proves quite useful in establishing an *algebra* of mixtures.

```{python}
SignatureEntry(copy_quantity).documentation()
```

```{python}
#| echo: true
air = copy_solution(solution)

air1 = ct.Quantity(air, mass=1.0)
air1.TPX = 373.15, None, newairs.X

air2 = copy_quantity(air1)
air2.TPX = 273.15, None, air2.X

mixair = air1 + air2
air1.T, air2.T, mixair.T
```

## NormalFlowRate

Common daily work activity for the process engineer is to perform mass balances, but wait, ..., gas flow rates are generally provided under normal conditions, and compositions may vary, so you need to compute normal densities first... whatever. This class provides a calculator wrapping a Cantera solution object so that your life gets easier.

```{python}
SignatureEntry(NormalFlowRate).documentation()
```

Its simples use case is as follows:

```{python}
#| echo: true
nfr = NormalFlowRate("airish.yaml")
print(f"Convert 1000 Nm³/h to {nfr(1000.0):.5f} kg/s")
```

If the database file default composition does not suit you, no problems:

```{python}
#| echo: true
nfr = NormalFlowRate("airish.yaml", X="N2: 1")
print(f"Convert 1000 Nm³/h to {nfr(1000.0):.5f} kg/s")
```

You can also print a nice report to inspect the details of internal state. For more, please check its API documentation.

```{python}
#| echo: true
print(nfr.report())
```

## Plug-flow reactors

### PlugFlowAxialSources

```{python}
SignatureEntry(PlugFlowAxialSources).documentation()
```

### PlugFlowChainCantera

```{python}
SignatureEntry(PlugFlowChainCantera).documentation()
```

<!-- TODO document methods -->

```{python}
SignatureEntry(get_reactor_data).documentation()
```