# Symbolic functions

*aka majordome_engineering.symbolic*

This module contains utilities for working with symbolic functions, especially in the context of engineering problems treated by Majordome models. It is mostly a wrapper around [CasADi](https://web.casadi.org/), organizing symbolic operations and providing additional functionality for function manipulation in a physical context.

```{python}
from majordome_utilities.documents import *
from majordome_engineering.symbolic import *
from majordome_utilities.plotting import plot2d
from casadi import SX, Function, jacobian
import cantera as ct
import numpy as np
```

## PiecewiseFunction

A major issue when working with symbolic expressions and real-world data is that they do not support flow-control constructs like `if` statements. This is a problem when we want to represent functions that are defined piecewise, especially when algorithmic differentiation is involved.

As an example, take the parameterization of [thermodynamic properties](https://cantera.org/stable/reference/thermo/species-thermo.html) of chemical species. For quantitative purposes, to ensure high accuracy, researchers have found that it is best to use different polynomial fits for different temperature ranges. This means that the thermodynamic properties of a species are defined as piecewise functions of temperature, which is a problem when we want to use them in a symbolic context.

To tackle this issue in *certain* contexts, `PiecewiseSymbolicFunction` provides an interpolation between different ranges of the domain of a function. Internally it makes use of Heaviside functions to ensure that the function is continuous. This is not a perfect solution, as it does not guarantee differentiability at the breakpoints, but it is a good compromise between accuracy and simplicity. It is also worth noting that this class is not meant to be used in a general context, but rather in specific contexts where the function is known to be well-behaved.

```{python}
doc = DocumentedClass(PiecewiseSymbolicFunction)
doc.constructor()
```

Let's illustrate its use with a simple example. We define two functions `f` and `g`, and we want to create a piecewise function that is equal to `f` for `x < 0.5` and equal to `g` for `x >= 0.5`. Functions have being created such that they evaluate to the same value at the breakpoint, as the practical case that led to the class development, *i.e.* NASA-parameterization of thermochemical properties. Below we show how to create the piecewise function, evaluate it numerically and symbolically, and compute its derivative symbolically.

```{python}
#| echo: true
# Define two simple functions:
f = lambda x: x**2
g = lambda x: f(0.5) + (x - 0.5)

# Create the piecewise function:
F = PiecewiseSymbolicFunction([0, 0.5, 1], [f, g])

# Evaluate numerically:
x = np.linspace(-0.2, 1.2, 100)
y = F(x)

# Evaluate symbolically:
T = SX.sym("T")
Y = F(T)

# Create a function for evaluating the derivative:
ydot = Function("fdot", [T], [jacobian(Y, T)])
```

Below we plot the piecewise function and its derivative. The function is continuous, but the derivative is not, as expected, although the transition is handled smoothly by the Heaviside functions. The red dashed line indicates the breakpoint at `x = 0.5`, where the function transitions from `f` to `g`.

```{python}
plot = plot2d(x, y, label="Piecewise function")
plot.axes[0].plot(x, ydot(x), label="Derivative")
plot.axes[0].axvline(0.5, color="r", linestyle="--")
plot.axes[0].legend(loc=2, fontsize="small")
plot.axes[0].set_ylim(-0.1, 1.1)
pass
```

## Symbolic species parameterization

```{python}
doc = DocumentedClass(SymbolicThermo)
doc.staticmethods()
```

Suppose you need to create a symbolic representation of the NASA7 thermodynamic parameterization of molecular nitrogen, species of index 47 in the GRI-Mech 3.0 mechanism shipped with Cantera. Let's start by loading and retrieving the thermodynamic data for this species.

```{python}
#| echo: true
gas = ct.Solution("gri30.yaml")
species = gas.species()[47]
thermo = species.thermo
```

Below we instantiate `SymbolicThermo` with the input data of the species. It is important to emphasize here that when building more complex systems, generally one should share the symbolic variables, *e.g.* temperature, across the different components of the system. For this reason, the constructor of symbolic thermodynamic classes expect the temperature symbol to be provided, instead of trying to create it internally; this is a design choice that will improve code robustness when handling mixtures and avoid many of the pitfalls of symbolic programming.

```{python}
#| echo: true
T = SX.sym("T")
nasa7 = SymbolicThermo.from_species(species, T)
```

::: {.callout-note title="Practical usage"}

You could instead directly instantiate `Nasa7Thermo` with the input data,  but using the factory method `SymbolicThermo.from_species` is a better choice, as it will allow you to easily switch to a different thermodynamic model. Furthermore, it is the safe choice for loading entire databases.

```python
nasa7 = Nasa7Thermo(T, species.thermo.input_data)

# This is just syntactic sugar for the above:
nasa7 = Nasa7Thermo.from_species(species, T)
```

:::

Here we illustrate the use of algorithmic differentiation to compute the derivative of the specific enthalpy with respect to temperature.

```{python}
#| echo: true
hdot = Function("hdot", [T], [jacobian(nasa7.h(T), T)])
```

The above derivative is  then confronted to the specific heat below:

```{python}
T_num = np.linspace(500, 2500, 100)

plot = plot2d(T_num, nasa7.cp(T_num), label="$c_{p}$")
plot.axes[0].plot(T_num[::5], hdot(T_num[::5]), "o", label="$dh/dT$")

for b in nasa7.breakpoints[1:-1]:
    plot.axes[0].axvline(b, color="r", linestyle="--")

plot.axes[0].set_xlabel("Temperature (K)")
plot.axes[0].set_ylabel("Dimensionless specific heat")
plot.axes[0].legend(loc=4)
pass
```

Finally, we compare the deviations between symbolic and numerical (Cantera) evaluation of the thermodynamic functions. This is not for error analysis, but a proof of correctness of the symbolic implementation.

```{python}
#| echo: true
# XXX: Cantera evaluates quantities per kmol! Divide by 1000 to get
# per mol, as the symbolic implementation does.
c_ct = np.array([0.001 * species.thermo.cp(T) for T in T_num])
h_ct = np.array([0.001 * species.thermo.h(T) for T in T_num])
s_ct = np.array([0.001 * species.thermo.s(T) for T in T_num])

error_c = np.mean(np.abs(nasa7._cp(T_num) - c_ct))
error_h = np.mean(np.abs(nasa7._h(T_num) - h_ct))
error_s = np.mean(np.abs(nasa7._s(T_num) - s_ct))

error_c, error_h, error_s
```

### Nasa7Thermo

```{python}
doc = DocumentedClass(Nasa7Thermo)
doc.constructor()
doc.staticmethods()
doc.classmethods()
```

## Symbolic mixture properties
